# Generated by Django 4.1.3 on 2023-01-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_lag_post_lat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Lag',
            new_name='Lng',
        ),
    ]
